name: Terraform ECR Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::528757804354:role/GitHubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd terraform-ecr
          terraform init

      - name: Terraform Apply
        run: |
          cd terraform-ecr
          terraform apply -auto-approve

      - name: Read Terraform Outputs
        run: |
          cd terraform-ecr
          terraform output

